import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://yoursite.com'

    return {
        rules: [
            {
                userAgent: '*',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog',
                    '/contact',
                    '/pricing',
                    '/features',
                    '/case-studies',
                    '/resources',
                    '/help',
                    '/support',
                    '/docs',
                    '/en/*',
                    '/es/*',
                    '/fr/*',
                    '/de/*',
                    '/it/*',
                    '/pt/*',
                    '/ja/*',
                    '/ko/*',
                    '/zh/*',
                    '/ar/*',
                    '/*.css',
                    '/*.js',
                    '/*.json',
                    '/*.xml',
                    '/*.png',
                    '/*.jpg',
                    '/*.jpeg',
                    '/*.gif',
                    '/*.svg',
                    '/*.webp',
                    '/*.ico',
                    '/*.woff',
                    '/*.woff2',
                    '/*.ttf',
                    '/*.eot',
                    '/favicon.ico',
                    '/robots.txt',
                    '/sitemap.xml'
                ],
                disallow: [
                    '/admin/*',
                    '/api/*',
                    '/dashboard/*',
                    '/user/*',
                    '/account/*',
                    '/profile/*',
                    '/settings/*',
                    '/auth/*',
                    '/login',
                    '/register',
                    '/reset-password',
                    '/verify-email',
                    '/private/*',
                    '/internal/*',
                    '/staging/*',
                    '/dev/*',
                    '/test/*',
                    '/tmp/*',
                    '/temp/*',
                    '/cache/*',
                    '/logs/*',
                    '/backup/*',
                    '/uploads/private/*',
                    '/uploads/temp/*',
                    '/downloads/private/*',
                    '/_next/*',
                    '/.next/*',
                    '/.git/*',
                    '/.env*',
                    '/node_modules/*',
                    '/package*.json',
                    '/yarn.lock',
                    '/pnpm-lock.yaml',
                    '/.vercel/*',
                    '/.netlify/*',
                    '/search',
                    '/search?*',
                    '/*?*utm_*',
                    '/*?*ref=*',
                    '/*?*source=*',
                    '/*?*campaign=*',
                    '/*?*fbclid=*',
                    '/*?*gclid=*',
                    '/*?*print=*',
                    '/*?*preview=*',
                    '/*?*debug=*',
                    '/cgi-bin/*',
                    '/wp-admin/*',
                    '/wp-content/*',
                    '/wp-includes/*',
                    '/xmlrpc.php',
                    '/trackback/*',
                    '/feed/*',
                    '/*.pdf$',
                    '/*.doc$',
                    '/*.docx$',
                    '/*.xls$',
                    '/*.xlsx$',
                    '/*.ppt$',
                    '/*.pptx$',
                    '/error',
                    '/404',
                    '/500',
                    '/maintenance'
                ],
                crawlDelay: 1
            },
            {
                userAgent: 'Googlebot',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog',
                    '/contact',
                    '/pricing',
                    '/features',
                    '/case-studies',
                    '/resources',
                    '/help',
                    '/support',
                    '/docs',
                    '/en/*',
                    '/es/*',
                    '/fr/*',
                    '/de/*',
                    '/it/*',
                    '/pt/*',
                    '/ja/*',
                    '/ko/*',
                    '/zh/*',
                    '/ar/*'
                ],
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/account/*',
                    '/profile/*',
                    '/settings/*',
                    '/auth/*',
                    '/private/*',
                    '/internal/*',
                    '/staging/*',
                    '/dev/*',
                    '/test/*',
                    '/search',
                    '/search?*',
                    '/*?*utm_*',
                    '/*?*ref=*',
                    '/*?*source=*',
                    '/*?*campaign=*',
                    '/*?*fbclid=*',
                    '/*?*gclid=*'
                ]
            },
            {
                userAgent: 'Bingbot',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog',
                    '/contact',
                    '/pricing',
                    '/features',
                    '/case-studies',
                    '/resources',
                    '/help',
                    '/support',
                    '/docs',
                    '/en/*',
                    '/es/*',
                    '/fr/*',
                    '/de/*'
                ],
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/private/*',
                    '/search',
                    '/*?*utm_*'
                ]
            },
            {
                userAgent: 'facebookexternalhit',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog/*',
                    '/case-studies/*',
                    '/resources/*'
                ],
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/private/*'
                ]
            },
            {
                userAgent: 'Twitterbot',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog/*',
                    '/case-studies/*',
                    '/resources/*'
                ],
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/private/*'
                ]
            },
            {
                userAgent: 'LinkedInBot',
                allow: [
                    '/',
                    '/about',
                    '/services',
                    '/products',
                    '/blog/*',
                    '/case-studies/*',
                    '/resources/*',
                    '/contact'
                ],
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/private/*'
                ]
            },
            {
                userAgent: [
                    'CCBot',
                    'ChatGPT-User',
                    'GPTBot',
                    'AI2Bot',
                    'aiHitBot',
                    'AI_Agent',
                    'Applebot-Extended',
                    'Apple-PubSub'
                ],
                disallow: ['/']
            },
            {
                userAgent: [
                    'SemrushBot',
                    'AhrefsBot',
                    'MJ12bot',
                    'DotBot',
                    'SiteAuditBot'
                ],
                crawlDelay: 10,
                disallow: [
                    '/api/*',
                    '/admin/*',
                    '/dashboard/*',
                    '/user/*',
                    '/private/*'
                ]
            }
        ],
        sitemap: [
            `${baseUrl}/sitemap.xml`,
            `${baseUrl}/sitemap-blog.xml`,
            `${baseUrl}/sitemap-products.xml`,
            `${baseUrl}/sitemap-services.xml`,
            `${baseUrl}/sitemap-en.xml`,
            `${baseUrl}/sitemap-es.xml`,
            `${baseUrl}/sitemap-fr.xml`,
            `${baseUrl}/sitemap-de.xml`,
            `${baseUrl}/sitemap-it.xml`,
            `${baseUrl}/sitemap-pt.xml`,
            `${baseUrl}/sitemap-ja.xml`,
            `${baseUrl}/sitemap-ko.xml`,
            `${baseUrl}/sitemap-zh.xml`,
            `${baseUrl}/sitemap-ar.xml`
        ],
        host: baseUrl
    }
}